Add response links support
Dorthu/openapi3 pull request #31
Opened 2021-01-25 05:31 UTC by guyarb

2021-01-25 08:27 UTC, barweiss requested changes

2021-01-25 08:27 UTC, barweiss commented on openapi3/paths.py
> +    .. _Response Object: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#linkObject
```suggestion
    .. _LinkObject: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#linkObject
```

2021-01-25 08:27 UTC, barweiss commented on openapi3/paths.py
> +    A `Link Object`_ describes a single Link from an API Operation Response to an API operation Request
Match case of "Operation"

2021-01-25 08:30 UTC, barweiss approved these changes

2021-01-26 04:15 UTC, guyarb commented on openapi3/paths.py
> +    .. _Response Object: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#linkObject
fixed

2021-01-26 04:15 UTC, guyarb commented on openapi3/paths.py
> +    A `Link Object`_ describes a single Link from an API Operation Response to an API operation Request
fixed

2021-07-12 05:31 UTC, guyarb commented
@Dorthu

2021-07-12 12:02 UTC, Dorthu commented
Sorry I missed this, takin' a look now

2021-07-12 12:31 UTC, Dorthu approved these changes
Looks good 👍   I'm going to follow this up with a few minor changes

Sorry it took so long for me to look at it, thanks for addition!

2021-07-12 12:31 UTC, merged

2021-07-12 13:31 UTC, Dorthu commented
This was released in 1.5.0 this morning